### ISSUE TITLE
Definition without Declaration of showLinks Function in libwot Namespace in wotc/wot.cpp:52

### ISSUE THREAD

**Issue by Idyllei** [ucoin-io/wotb#5]
I was looking through the wotb code on my local clone of the repository, and I couldn't find the definition of `showLinks` anywhere within the wotb codebase.  

Is this intentional (e.g. it is defined in an imported header)?

Here is a link to the function definition: [wotb/wotc/wot.cpp Line:52](https://github.com/ucoin-io/wotb/blob/master/wotc/wot.cpp#L52). 

Ive added a pull request to fix the issue: #4 .

**Comment by c-geek** [comment]
Fixed, thanks!
